### ISSUE TITLE
I am getting error while importing the model

### ISSUE THREAD

**Issue by nvmaditya** [kyutai-labs/delayed-streams-modeling#112]
### Due diligence

- [x] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

I am getting this error, any idea how to fix this?

tokenizer_spm_8k_en_fr_audio.model: 100% 120k/120k [00:00<00:00, 292MB/s]
Traceback (most recent call last):
  File "/content/Kyutai-TTS-Colab/app.py", line 12, in <module>
    tts_model = TTSModel.from_checkpoint_info(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/moshi/models/tts.py", line 396, in from_checkpoint_info
    mimi = checkpoint_info.get_mimi(device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/moshi/models/loaders.py", line 262, in get_mimi
    return get_mimi(self.mimi_weights, num_codebooks=num_codebooks, device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/moshi/models/loaders.py", line 325, in get_mimi
    load_model(model, filename, device=str(device))
  File "/usr/local/lib/python3.11/dist-packages/safetensors/torch.py", line 271, in load_model
    raise RuntimeError(error)
RuntimeError: Error(s) in loading state_dict for MimiModel:
    Missing key(s) in state_dict: "decoder_transformer.transformer.layers.0.self_attn.in_projs.0.weight", "decoder_transformer.transformer.layers.0.self_attn.out_projs.0.weight", "decoder_transformer.transformer.layers.1.self_attn.in_projs.0.weight", "decoder_transformer.transformer.layers.1.self_attn.out_projs.0.weight", "decoder_transformer.transformer.layers.2.self_attn.in_projs.0.weight", "decoder_transformer.transformer.layers.2.self_attn.out_projs.0.weight", "decoder_transformer.transformer.layers.3.self_attn.in_projs.0.weight", "decoder_transformer.transformer.layers.3.self_attn.out_projs.0.weight", "decoder_transformer.transformer.layers.4.self_attn.in_projs.0.weight", "decoder_transformer.transformer.layers.4.self_attn.out_projs.0.weight", "decoder_transformer.transformer.layers.5.self_attn.in_projs.0.weight", "decoder_transformer.transformer.layers.5.self_attn.out_projs.0.weight", "decoder_transformer.transformer.layers.6.self_attn.in_projs.0.weight", "decoder_transformer.transformer.layers.6.self_attn.out_projs.0.weight", "decoder_transformer.transformer.layers.7.self_attn.in_projs.0.weight", "decoder_transformer.transformer.layers.7.self_attn.out_projs.0.weight", "encoder_transformer.transformer.layers.0.self_attn.in_projs.0.weight", "encoder_transformer.transformer.layers.0.self_attn.out_projs.0.weight", "encoder_transformer.transformer.layers.1.self_attn.in_projs.0.weight", "encoder_transformer.transformer.layers.1.self_attn.out_projs.0.weight", "encoder_transformer.transformer.layers.2.self_attn.in_projs.0.weight", "encoder_transformer.transformer.layers.2.self_attn.out_projs.0.weight", "encoder_transformer.transformer.layers.3.self_attn.in_projs.0.weight", "encoder_transformer.transformer.layers.3.self_attn.out_projs.0.weight", "encoder_transformer.transformer.layers.4.self_attn.in_projs.0.weight", "encoder_transformer.transformer.layers.4.self_attn.out_projs.0.weight", "encoder_transformer.transformer.layers.5.self_attn.in_projs.0.weight", "encoder_transformer.transformer.layers.5.self_attn.out_projs.0.weight", "encoder_transformer.transformer.layers.6.self_attn.in_projs.0.weight", "encoder_transformer.transformer.layers.6.self_attn.out_projs.0.weight", "encoder_transformer.transformer.layers.7.self_attn.in_projs.0.weight", "encoder_transformer.transformer.layers.7.self_attn.out_projs.0.weight"
    Unexpected key(s) in state_dict: "decoder_transformer.transformer.layers.0.self_attn.in_proj_weight", "decoder_transformer.transformer.layers.0.self_attn.out_proj.weight", "decoder_transformer.transformer.layers.1.self_attn.in_proj_weight", "decoder_transformer.transformer.layers.1.self_attn.out_proj.weight", "decoder_transformer.transformer.layers.2.self_attn.in_proj_weight", "decoder_transformer.transformer.layers.2.self_attn.out_proj.weight", "decoder_transformer.transformer.layers.3.self_attn.in_proj_weight", "decoder_transformer.transformer.layers.3.self_attn.out_proj.weight", "decoder_transformer.transformer.layers.4.self_attn.in_proj_weight", "decoder_transformer.transformer.layers.4.self_attn.out_proj.weight", "decoder_transformer.transformer.layers.5.self_attn.in_proj_weight", "decoder_transformer.transformer.layers.5.self_attn.out_proj.weight", "decoder_transformer.transformer.layers.6.self_attn.in_proj_weight", "decoder_transformer.transformer.layers.6.self_attn.out_proj.weight", "decoder_transformer.transformer.layers.7.self_attn.in_proj_weight", "decoder_transformer.transformer.layers.7.self_attn.out_proj.weight", "encoder_transformer.transformer.layers.0.self_attn.in_proj_weight", "encoder_transformer.transformer.layers.0.self_attn.out_proj.weight", "encoder_transformer.transformer.layers.1.self_attn.in_proj_weight", "encoder_transformer.transformer.layers.1.self_attn.out_proj.weight", "encoder_transformer.transformer.layers.2.self_attn.in_proj_weight", "encoder_transformer.transformer.layers.2.self_attn.out_proj.weight", "encoder_transformer.transformer.layers.3.self_attn.in_proj_weight", "encoder_transformer.transformer.layers.3.self_attn.out_proj.weight", "encoder_transformer.transformer.layers.4.self_attn.in_proj_weight", "encoder_transformer.transformer.layers.4.self_attn.out_proj.weight", "encoder_transformer.transformer.layers.5.self_attn.in_proj_weight", "encoder_transformer.transformer.layers.5.self_attn.out_proj.weight", "encoder_transformer.transformer.layers.6.self_attn.in_proj_weight", "encoder_transformer.transformer.layers.6.self_attn.out_proj.weight", "encoder_transformer.transformer.layers.7.self_attn.in_proj_weight", "encoder_transformer.transformer.layers.7.self_attn.out_proj.weight"

**Comment by LaurentMazare** [comment]
Could you provide a way to replicate the issue? Just looking at the error, it seems that the mimi safetensor file doesn't have the expected tensor naming convention but it's tricky to understand what could be causing this.

**Comment by AdixSasuke** [comment]
I was trying to run this gradio which i got from youtube
[https://colab.research.google.com/github/NeuralFalconYT/Kyutai-TTS-Colab/blob/main/Kyutai_TTS.ipynb#scrollTo=z7hr889ORwWc](https://colab.research.google.com/github/NeuralFalconYT/Kyutai-TTS-Colab/blob/main/Kyutai_TTS.ipynb#scrollTo=z7hr889ORwWc)

**Comment by LaurentMazare** [comment]
This seems to be caused by a recent change in safetensors that prevent the load hooks to be run when loading the weights, see https://github.com/huggingface/safetensors/issues/645
While this is investigated further, you should hopefully be able to use the `safetensors` version that moshi expects by running the following:
```
!pip install safetensors==0.4.4 --force-reinstall
```

**Comment by adefossez** [comment]
should be fixed with https://github.com/kyutai-labs/moshi/pull/366

**Comment by icemagno** [comment]
I'm in ComfyUI and still receiving this error. Changing to Kokoro Audio. Sorry !
